# 激活的配置文件(默认dev,打包时会被Maven profile替换)
spring:
  profiles:
    active: @spring.profiles.active@
  config:
    import: classpath:config/redis/redis-key.yml

# MyBatis 配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.gis.basic_template_not_login_back.entity
  configuration:
    map-underscore-to-camel-case: true